name: PR check
on: [pull_request]
jobs:
  testAllModes:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: /
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test results
        path: artifacts
